import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';

import pg from 'pg';

import { createHealthArchiveRepository } from '../lib/archive/repository.js';
import { runCompactHealthOperation } from '../lib/db/compact-backfill.js';
import { createCompactMetricWriter } from '../lib/db/compact-metric-writer.js';
import { applyMigrations } from '../lib/db/migrations.js';
import { createMetricWriter } from '../lib/db/metric-writer.js';
import { createSyncRepository } from '../lib/jobs/sync-repository.js';
import { createSyncService } from '../lib/jobs/sync-service.js';

const integrationUrl = process.env.PG_INTEGRATION_URL;
const integrationSchemaPrefix = 'health_archive_integration_';

function createIntegrationSchemaName() {
  return `${integrationSchemaPrefix}${randomUUID().replaceAll('-', '')}`;
}

function quoteIntegrationSchema(schema) {
  if (!new RegExp(`^${integrationSchemaPrefix}[a-f0-9]{32}$`).test(schema)) {
    throw new Error('Integration schema must be generated by this test harness');
  }

  return `"${schema}"`;
}

function integrationSchemaToDrop(schema, schemaWasCreated) {
  return schemaWasCreated ? quoteIntegrationSchema(schema) : null;
}

test('PostgreSQL integration harness uses only a generated isolated schema', () => {
  const schema = createIntegrationSchemaName();

  assert.match(schema, /^health_archive_integration_[a-f0-9]{32}$/);
  assert.equal(quoteIntegrationSchema(schema), `"${schema}"`);
  assert.throws(() => quoteIntegrationSchema('public'), /must be generated/);
  assert.equal(integrationSchemaToDrop(schema, false), null);
  assert.equal(integrationSchemaToDrop(schema, true), `"${schema}"`);
});

test('PostgreSQL verified-month pruning deletes compact rows in bounded authorized batches', { skip: !integrationUrl }, async () => {
  const pool = new pg.Pool({ connectionString: integrationUrl });
  const schema = createIntegrationSchemaName();
  const quotedSchema = quoteIntegrationSchema(schema);
  let client;
  let schemaWasCreated = false;

  try {
    await pool.query(`CREATE SCHEMA ${quotedSchema}`);
    schemaWasCreated = true;
    await applyMigrations(pool, { schema });
    client = await pool.connect();
    await client.query(`SET search_path TO ${quotedSchema}`);
    const accountId = '11111111-1111-1111-1111-111111111111';
    const streamId = '22222222-2222-2222-2222-222222222222';
    const catalogId = '33333333-3333-3333-3333-333333333333';
    await client.query(
      `INSERT INTO source_accounts (id, provider, provider_account_id)
       VALUES ($1, 'archive-test', 'prune-integration')`,
      [accountId],
    );
    await client.query(
      `INSERT INTO source_streams (id, source_account_id, metadata, metadata_hash)
       VALUES ($1, $2, '{"dataType":"heart-rate"}', $3)`,
      [streamId, accountId, 'a'.repeat(64)],
    );
    await client.query(
      `INSERT INTO heart_rate_samples_compact
         (source_account_id, source_stream_id, civil_date, sampled_at, beats_per_minute)
       VALUES ($1, $2, '2026-01-02', '2026-01-02T12:00:00Z', 70)`,
      [accountId, streamId],
    );
    await client.query(
      `INSERT INTO calorie_intervals_compact
         (source_account_id, source_stream_id, civil_date, interval_type,
          start_at, end_at, kilocalories)
       VALUES ($1, $2, '2026-01-02', 'active',
               '2026-01-02T12:00:00Z', '2026-01-02T12:05:00Z', 0)`,
      [accountId, streamId],
    );
    await client.query(
      `INSERT INTO health_archive_catalog
         (id, source_account_id, archive_month, archive_version, state,
          heart_sample_count, calorie_interval_count, verified_at)
       VALUES ($1, $2, '2026-01-01', 1, 'verified', 1, 1, CURRENT_TIMESTAMP)`,
      [catalogId, accountId],
    );

    const removed = await createHealthArchiveRepository(client)
      .pruneVerifiedMonth(catalogId, { batchSize: 1 });

    assert.equal(removed.compactHeartRateSamples, 1);
    assert.equal(removed.compactCalorieIntervals, 1);
    assert.equal(
      Number((await client.query('SELECT COUNT(*) AS count FROM heart_rate_samples_compact')).rows[0].count),
      0,
    );
    assert.equal(
      (await client.query('SELECT state FROM health_archive_catalog WHERE id = $1', [catalogId])).rows[0].state,
      'pruned',
    );
  } finally {
    client?.release();
    if (schemaWasCreated) await pool.query(`DROP SCHEMA ${quotedSchema} CASCADE`);
    await pool.end();
  }
});

test('PostgreSQL integration applies the lifelong archive schema and constraints', { skip: !integrationUrl }, async () => {
  const pool = new pg.Pool({ connectionString: integrationUrl });
  const schema = createIntegrationSchemaName();
  const quotedSchema = quoteIntegrationSchema(schema);
  let client;
  let schemaWasCreated = false;

  try {
    await pool.query(`CREATE SCHEMA ${quotedSchema}`);
    schemaWasCreated = true;
    await applyMigrations(pool, { schema });
    client = await pool.connect();
    await client.query(`SET search_path TO ${quotedSchema}`);

    const version = await client.query('SHOW server_version_num');
    assert.ok(Number(version.rows[0].server_version_num) >= 160000);

    const index = await client.query(`
      SELECT indexdef
      FROM pg_indexes
      WHERE schemaname = $1
        AND indexname = 'heart_rate_samples_compact_access_idx'
    `, [schema]);
    assert.match(index.rows[0].indexdef, /INCLUDE \(source_stream_id, utc_offset_seconds, beats_per_minute, upstream_sample_id\)/);

    const accountId = '11111111-1111-1111-1111-111111111111';
    const streamId = '22222222-2222-2222-2222-222222222222';
    await client.query(
      `INSERT INTO source_accounts (id, provider, provider_account_id) VALUES ($1, 'google', 'integration-account')`,
      [accountId],
    );
    await client.query(
      `INSERT INTO source_streams (id, source_account_id, metadata, metadata_hash)
       VALUES ($1, $2, '{"dataType":"heart-rate"}', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')`,
      [streamId, accountId],
    );
    await assert.rejects(
      client.query(
        `INSERT INTO source_streams (id, source_account_id, metadata, metadata_hash)
         VALUES ('33333333-3333-3333-3333-333333333333', $1, '{}', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')`,
        [accountId],
      ),
      { code: '23505' },
    );

    await client.query(
      `INSERT INTO heart_rate_samples_compact
        (source_account_id, source_stream_id, civil_date, sampled_at, utc_offset_seconds, beats_per_minute)
       VALUES ($1, $2, '2026-07-01', '2026-07-01T12:00:00Z', -14400, 70)`,
      [accountId, streamId],
    );
    await assert.rejects(
      client.query(
        `INSERT INTO heart_rate_samples_compact
          (source_account_id, source_stream_id, civil_date, sampled_at, utc_offset_seconds, beats_per_minute)
         VALUES ($1, $2, '2026-07-01', '2026-07-01T12:00:00Z', -14400, 71)`,
        [accountId, streamId],
      ),
      { code: '23505' },
    );
    await assert.rejects(
      client.query(
        `INSERT INTO heart_rate_samples_compact
          (source_account_id, source_stream_id, civil_date, sampled_at, utc_offset_seconds, beats_per_minute)
         VALUES ($1, $2, '2026-07-01', '2026-07-01T13:00:00Z', -14400, 0)`,
        [accountId, streamId],
      ),
      { code: '23514' },
    );

    await client.query(
      `INSERT INTO calorie_intervals_compact
        (source_account_id, source_stream_id, civil_date, interval_type, start_at, end_at, utc_offset_seconds, kilocalories)
       VALUES ($1, $2, '2026-07-01', 'active', '2026-07-01T12:00:00Z', '2026-07-01T12:05:00Z', -14400, 10)`,
      [accountId, streamId],
    );
    await assert.rejects(
      client.query(
        `INSERT INTO calorie_intervals_compact
          (source_account_id, source_stream_id, civil_date, interval_type, start_at, end_at, utc_offset_seconds, kilocalories)
         VALUES ($1, $2, '2026-07-01', 'basal', '2026-07-01T12:15:00Z', '2026-07-01T12:15:00Z', -14400, 1)`,
        [accountId, streamId],
      ),
      { code: '23514' },
    );
    await client.query(
      `UPDATE calorie_intervals_compact
       SET end_at = '2026-07-01T12:10:00Z', kilocalories = 11
       WHERE source_stream_id = $1
         AND interval_type = 'active'
         AND start_at = '2026-07-01T12:00:00Z'`,
      [streamId],
    );
    const correctedInterval = await client.query(
      `SELECT end_at, kilocalories
       FROM calorie_intervals_compact
       WHERE source_stream_id = $1`,
      [streamId],
    );
    assert.equal(correctedInterval.rows[0].end_at.toISOString(), '2026-07-01T12:10:00.000Z');
    assert.equal(Number(correctedInterval.rows[0].kilocalories), 11);

    await client.query(
      `INSERT INTO health_archive_catalog
        (id, source_account_id, archive_month, archive_version, is_active, state, heart_sample_count, calorie_interval_count)
       VALUES ('44444444-4444-4444-4444-444444444444', $1, '2026-07-01', 1, true, 'verified', 1, 1)`,
      [accountId],
    );
    await assert.rejects(
      client.query(
        `INSERT INTO health_archive_catalog
          (id, source_account_id, archive_month, archive_version, is_active, state, heart_sample_count, calorie_interval_count)
         VALUES ('55555555-5555-5555-5555-555555555555', $1, '2026-07-01', 2, true, 'verified', 1, 1)`,
        [accountId],
      ),
      { code: '23505' },
    );
    await client.query(
      `INSERT INTO health_archive_catalog
        (id, source_account_id, archive_month, archive_version, is_active, state, heart_sample_count, calorie_interval_count)
       VALUES ('66666666-6666-6666-6666-666666666666', $1, '2026-07-01', 2, false, 'superseded', 1, 1)`,
      [accountId],
    );
    for (const [id, archiveMonth, archiveVersion, heartCount, byteSize, startedAt, endedAt] of [
      ['77777777-7777-7777-7777-777777777777', '2026-07-02', 1, 0, null, null, null],
      ['88888888-8888-8888-8888-888888888888', '2026-08-01', 0, 0, null, null, null],
      ['99999999-9999-9999-9999-999999999999', '2026-08-01', 1, -1, null, null, null],
      ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '2026-08-01', 1, 0, -1, null, null],
      ['bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '2026-08-01', 1, 0, null, '2026-08-02T00:00:00Z', '2026-08-01T00:00:00Z'],
    ]) {
      await assert.rejects(
        client.query(
          `INSERT INTO health_archive_catalog
            (id, source_account_id, archive_month, archive_version, is_active, state,
             heart_sample_count, calorie_interval_count, byte_size, measurement_started_at, measurement_ended_at)
           VALUES ($1, $2, $3, $4, false, 'failed', $5, 0, $6, $7, $8)`,
          [id, accountId, archiveMonth, archiveVersion, heartCount, byteSize, startedAt, endedAt],
        ),
        { code: '23514' },
      );
    }
  } finally {
    client?.release();
    const schemaToDrop = integrationSchemaToDrop(schema, schemaWasCreated);
    if (schemaToDrop) await pool.query(`DROP SCHEMA ${schemaToDrop} CASCADE`);
    await pool.end();
  }
});

test('PostgreSQL compact writes are set-based no-ops for identical rows and update corrections once', { skip: !integrationUrl }, async () => {
  const pool = new pg.Pool({ connectionString: integrationUrl });
  const schema = createIntegrationSchemaName();
  const quotedSchema = quoteIntegrationSchema(schema);
  let client;
  let schemaWasCreated = false;

  try {
    await pool.query(`CREATE SCHEMA ${quotedSchema}`);
    schemaWasCreated = true;
    await applyMigrations(pool, { schema });
    client = await pool.connect();
    await client.query(`SET search_path TO ${quotedSchema}`);
    const accountId = '11111111-1111-1111-1111-111111111111';
    await client.query(
      `INSERT INTO source_accounts (id, provider, provider_account_id)
       VALUES ($1, 'google-health', 'compact-integration')`,
      [accountId],
    );
    const writer = createCompactMetricWriter(client);
    const watch = {
      civilDate: '2026-11-01',
      sampledAt: '2026-11-01T05:30:00Z',
      utcOffsetSeconds: -14400,
      beatsPerMinute: 61,
      providerId: 'watch-sample',
      device: { model: 'Watch' },
      sourceFields: { dataSource: { device: { model: 'Watch' } } },
      sourceMetadata: { dataType: 'heart-rate', dataSource: { device: { model: 'Watch' } } },
    };
    const ring = {
      ...watch,
      providerId: 'ring-sample',
      device: { model: 'Ring' },
      sourceFields: { dataSource: { device: { model: 'Ring' } } },
      sourceMetadata: { dataSource: { device: { model: 'Ring' } }, dataType: 'heart-rate' },
    };
    const watchNextDay = {
      ...watch,
      civilDate: '2026-11-02',
      sampledAt: '2026-11-02T06:30:00Z',
      utcOffsetSeconds: -18000,
      beatsPerMinute: 63,
      providerId: 'watch-sample-next-day',
    };

    assert.deepEqual(await writer.upsertHeartSamples(accountId, [watch, watchNextDay, ring]), {
      inserted: 3,
      updated: 0,
      unchanged: 0,
    });
    const before = await client.query(
      `SELECT heart.source_stream_id, heart.sampled_at, heart.xmin::text AS xmin, stream.metadata
       FROM heart_rate_samples_compact AS heart
       JOIN source_streams AS stream ON stream.id = heart.source_stream_id
       ORDER BY heart.source_stream_id, heart.sampled_at`,
    );
    assert.deepEqual(await writer.upsertHeartSamples(accountId, [watch, watchNextDay, ring]), {
      inserted: 0,
      updated: 0,
      unchanged: 3,
    });
    const unchanged = await client.query(
      `SELECT heart.source_stream_id, heart.sampled_at, heart.xmin::text AS xmin, stream.metadata
       FROM heart_rate_samples_compact AS heart
       JOIN source_streams AS stream ON stream.id = heart.source_stream_id
       ORDER BY heart.source_stream_id, heart.sampled_at`,
    );
    assert.deepEqual(unchanged.rows, before.rows);

    assert.deepEqual(
      await writer.upsertHeartSamples(accountId, [{ ...watch, beatsPerMinute: 64 }]),
      { inserted: 0, updated: 1, unchanged: 0 },
    );
    const watchBefore = before.rows.find(
      ({ metadata, sampled_at: sampledAt }) =>
        metadata.dataSource.device.model === 'Watch' &&
        sampledAt.toISOString() === '2026-11-01T05:30:00.000Z',
    );
    const corrected = await client.query(
      `SELECT beats_per_minute, xmin::text AS xmin
       FROM heart_rate_samples_compact
       WHERE source_stream_id = $1 AND sampled_at = $2`,
      [watchBefore.source_stream_id, watch.sampledAt],
    );
    assert.equal(Number(corrected.rows[0].beats_per_minute), 64);
    assert.notEqual(corrected.rows[0].xmin, watchBefore.xmin);

    const activeZero = {
      civilDate: '2026-11-01',
      metricType: 'active',
      startTime: '2026-11-01T05:00:00Z',
      endTime: '2026-11-01T06:00:00Z',
      utcOffsetSeconds: -14400,
      kilocalories: 0,
      providerId: 'active-zero',
      device: { model: 'Watch' },
      sourceFields: { dataSource: { device: { model: 'Watch' } } },
      sourceMetadata: {
        dataType: 'active-energy-burned',
        dataSource: { device: { model: 'Watch' } },
      },
    };
    assert.deepEqual(await writer.upsertCalorieIntervals(accountId, [activeZero]), {
      inserted: 1,
      updated: 0,
      unchanged: 0,
    });
    const zero = await client.query('SELECT kilocalories FROM calorie_intervals_compact');
    assert.equal(Number(zero.rows[0].kilocalories), 0);

    const legacyWriter = createMetricWriter(client, { clientOwnedByCaller: true });
    await legacyWriter.upsertHeartSamples(accountId, [
      { ...watch, providerKey: 'legacy-watch', beatsPerMinute: 64 },
      { ...watchNextDay, providerKey: 'legacy-watch-next-day' },
      { ...ring, providerKey: 'legacy-ring' },
    ]);
    await legacyWriter.upsertCalorieIntervals(accountId, [
      { ...activeZero, providerKey: 'legacy-active-zero' },
    ]);
    await legacyWriter.recalculateDaily(accountId, '2026-11-01');
    await legacyWriter.recalculateDaily(accountId, '2026-11-02');
    assert.deepEqual(await runCompactHealthOperation({ pool: client, mode: 'validate' }), {
      valid: true,
      mismatches: { heart: [], calories: [] },
    });

    await client.query(
      `UPDATE calorie_daily_summaries SET total_kcal = 999
       WHERE source_account_id = $1 AND civil_date = '2026-11-01'`,
      [accountId],
    );
    const staleDailyValidation = await runCompactHealthOperation({ pool: client, mode: 'validate' });
    assert.equal(staleDailyValidation.valid, false);
    assert.equal(staleDailyValidation.mismatches.calories.length, 1);

    await legacyWriter.recalculateDaily(accountId, '2026-11-01');
    await client.query(
      `UPDATE calorie_intervals_compact SET interval_type = 'basal'
       WHERE source_account_id = $1 AND civil_date = '2026-11-01' AND interval_type = 'active'`,
      [accountId],
    );
    const typeSwapValidation = await runCompactHealthOperation({ pool: client, mode: 'validate' });
    assert.equal(typeSwapValidation.valid, false);
    assert.equal(typeSwapValidation.mismatches.calories.length, 1);
  } finally {
    client?.release();
    if (schemaWasCreated) await pool.query(`DROP SCHEMA ${quotedSchema} CASCADE`);
    await pool.end();
  }
});

test('PostgreSQL repeated two-day syncs are compact no-ops and finalize each date once per job', { skip: !integrationUrl }, async () => {
  const pool = new pg.Pool({ connectionString: integrationUrl });
  const schema = createIntegrationSchemaName();
  const quotedSchema = quoteIntegrationSchema(schema);
  let client;
  let schemaWasCreated = false;

  try {
    await pool.query(`CREATE SCHEMA ${quotedSchema}`);
    schemaWasCreated = true;
    await applyMigrations(pool, { schema });
    client = await pool.connect();
    await client.query(`SET search_path TO ${quotedSchema}`);
    const query = client.query.bind(client);
    const database = {
      query,
      async connect() {
        return { query, release() {} };
      },
    };
    const accountId = '22222222-2222-2222-2222-222222222222';
    await database.query(
      `INSERT INTO source_accounts (
        id, provider, provider_account_id, timezone, membership_start_date
      ) VALUES ($1, 'google-health', 'repeat-sync', 'America/Toronto', '2026-01-01')`,
      [accountId],
    );

    const compactResults = [];
    const compactWriter = createCompactMetricWriter(database);
    const recordingCompactWriter = {
      async upsertHeartSamples(...args) {
        const result = await compactWriter.upsertHeartSamples(...args);
        compactResults.push(result);
        return result;
      },
      async upsertCalorieIntervals(...args) {
        return compactWriter.upsertCalorieIntervals(...args);
      },
    };
    const baseWriter = createMetricWriter(database, {
      compactWritesEnabled: true,
      compactWriter: recordingCompactWriter,
    });
    const finalizedDates = [];
    const writer = {
      ...baseWriter,
      async recalculateDaily(sourceAccountId, date, transaction) {
        const result = await baseWriter.recalculateDaily(sourceAccountId, date, transaction);
        finalizedDates.push(date);
        return result;
      },
    };
    const service = createSyncService({
      pool: database,
      repository: createSyncRepository(database, { advisoryLocks: false }),
      writer,
      gateway: {
        async request({ pageToken }) {
          const civilDate = pageToken ? '2026-07-17' : '2026-07-16';
          return {
            data: {
              dataPoints: [{
                dataPointName: `repeat-heart-${civilDate}`,
                heartRate: {
                  samples: [{
                    sampleTime: `${civilDate}T12:00:00Z`,
                    utcOffset: '-14400s',
                    beatsPerMinute: civilDate.endsWith('16') ? 71 : 72,
                  }],
                },
              }],
            },
            nextPageToken: pageToken ? null : 'second-day',
          };
        },
      },
    });

    async function runTwoPageJob(expectedFinalizationsAfterFirstPage) {
      await service.enqueue({
        mode: 'custom',
        startDate: '2026-07-16',
        endDateExclusive: '2026-07-18',
        metrics: ['heart-rate'],
      });
      await service.runOnce();
      assert.equal(finalizedDates.length, expectedFinalizationsAfterFirstPage);
      await service.runOnce();
      assert.equal((await service.status()).recent[0].status, 'completed');
    }

    await runTwoPageJob(0);
    await runTwoPageJob(2);

    assert.deepEqual(compactResults.slice(0, 2), [
      { inserted: 1, updated: 0, unchanged: 0 },
      { inserted: 1, updated: 0, unchanged: 0 },
    ]);
    assert.deepEqual(compactResults.slice(2), [
      { inserted: 0, updated: 0, unchanged: 1 },
      { inserted: 0, updated: 0, unchanged: 1 },
    ]);
    assert.deepEqual(finalizedDates, [
      '2026-07-16',
      '2026-07-17',
      '2026-07-16',
      '2026-07-17',
    ]);
    assert.equal(
      Number((await database.query('SELECT COUNT(*) AS count FROM heart_rate_samples_compact')).rows[0].count),
      2,
    );
  } finally {
    client?.release();
    if (schemaWasCreated) await pool.query(`DROP SCHEMA ${quotedSchema} CASCADE`);
    await pool.end();
  }
});
